<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Framework Quickstart Application</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  </head>
  <body>
    <div class="sidebar">
      <div class="block">
        <p>
          Autem Ego dico vobis: diligite vestros inimicos, 
          benefacite his, qui oderunt vos,
          et orate pro persequentibus et calumniantibus vos.
        </p>
      </div>
      <div class="block">
        <ul>
          <li><a href="https://www.youtube.com/" target="_blank">YouTube</a></li>
          <li><a href="https://www.facebook.com/" target="_blank">FaceBook</a></li>
        </ul>
      </div>
    </div>
    <div id="header" style="background-color: #EEEEEE; height: 30px;">
      <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
      </div>
      <div id="header-navigation" style="float: right">
        <a href="<?php
        echo $this->url(
          array('controller' => 'guestbook'), 'default', true)
        ?>">Guestbook</a>
      </div>
    </div>

    <?php echo $this->layout()->content ?>

  </body>
</html>